name: Deploy Canopy
description: 'Composite action for deployment steps'

on:
  workflow_call:

runs:
  using: 'composite'
#jobs:
#  deploy_canopy:
  steps:
    - name: Install dependencies
      shell: bash
      run: npm i

    - name: Build API
      shell: bash
      run: npm run build:ts

    - name: Build Apps
      shell: bash
      run: npm run build:apps

    - name: Deploy with rsync
      shell: bash
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzc --delete --exclude="*.ts" --exclude=".git"
        path: ./
        remote_path: ${{ input.TARGET_DIR }}
        remote_host: ${{ input.HOST }}
        remote_user: ${{ input.USER }}
        remote_key: ${{ input.SSH_KEY }}

    - name: Restart Canopy
      shell: bash
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ input.HOST }}
        username: ${{ input.USER }}
        key: ${{ input.SSH_KEY }}
        port: 22
        script: pm2 restart canopy

