name: Deploy Canopy
description: 'Composite action for deployment steps'

on:
  workflow_call:

jobs:
  deploy_canopy:
  secrets: inherit
  steps:
    - name: Install dependencies
      run: npm i

    - name: Build API
      run: npm run build:ts

    - name: Build Apps
      run: npm run build:apps

    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzc --delete --exclude="*.ts" --exclude=".git"
        path: ./
        remote_path: ${{ secrets.TARGET_DIR }}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USER }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Restart Canopy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: pm2 restart canopy

