/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as ResumeResumeIdImport } from "./routes/resume/$resumeId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const ResumeResumeIdRoute = ResumeResumeIdImport.update({
	path: "/resume/$resumeId",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/resume/$resumeId": {
			id: "/resume/$resumeId";
			path: "/resume/$resumeId";
			fullPath: "/resume/$resumeId";
			preLoaderRoute: typeof ResumeResumeIdImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
	IndexRoute,
	ResumeResumeIdRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/conductors/$resumeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/conductors/$resumeId": {
      "filePath": "conductors/$resumeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
