name: api

on:
  push:
    paths:
      - 'src/api/**'
      - 'src/tools/**'
      - 'src/utils/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BLUR: ${{ secrets.BLUR }}
      PORT: ${{ secrets.PORT }}
      API_KEY: ${{ secrets.API_KEY }}
      APP_ENV: ${{ secrets.APP_ENV }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i
#
      - name: Build application
        run: npm run build:ts