name: Deploying Canopy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BLUR: ${{ secrets.BLUR }}
      APP_ENV: ${{ secrets.APP_ENV }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i
#
      - name: Build application
        run: PORT=${{ secrets.PORT }} APP_ENV=${{ secrets.APP_ENV }} npm run build

      - name: Bundle files for transfer
        run: |
          tar -czvf ${{ secrets.BUNDLE_NAME }} src public node_modules package.json next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json tsup.config.ts;

      - name: SCP file transfer
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ secrets.BUNDLE_NAME }}
          host: ${{ secrets.HOST }}
          remote: ${{ secrets.TARGET_DIR }}
          port: 22
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}

      - name: Unpack Bundle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.TARGET_DIR }};
            tar -xzvf ${{ secrets.BUNDLE_NAME }};
            rm ${{ secrets.BUNDLE_NAME }};
            pm2 restart canopy
      - name: Get commit details
        id: commit_details
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          COMMIT_HASH=$(git log -1 --pretty=format:'%H')
          echo "COMMIT_TITLE=$COMMIT_TITLE" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          npm run discord -- \
            --url ${{ github.server_url }}/${{ github.repository }}/commit/${{ env.COMMIT_HASH }} \
            --level success \
            --title ${{ env.COMMIT_TITLE }} \
            --author.url https://github.com/${{ github.actor }} \
            --author.name ${{ github.actor }} \
            --author.avatar ${{ github.event.sender.avatar_url }} \
            --description "${{ github.repository }} deploy status: 🎉 SUCCESS  🎉" \
            --field "Branch%${{ github.ref }}%true" \
            --field "Commit%${{ env.COMMIT_TITLE }}%false" \
            --field "Commit Hash%${{ env.COMMIT_HASH }}%true"

      - name: Notify Discord Catch All
        if: ${{ failure() }}
        run: |
          npm run discord -- \
            --url ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} \
            --level critical \
            --title ${{ env.COMMIT_TITLE }} \
            --author.url https://github.com/${{ github.actor }} \
            --author.name ${{ github.actor }} \
            --author.avatar ${{ github.event.sender.avatar_url }} \
            --description "${{ github.repository }} deploy status: 🚨 FAILURE  🚨"
            --field "Branch%${{ github.ref }}%true" \
            --field "Commit%${{ env.COMMIT_TITLE }}%false" \
            --field "Commit Hash%${{ env.COMMIT_HASH }}%true"