name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures all history is fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check for changes
        id: check_for_changes
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            BASE_SHA=$(git rev-parse HEAD^)
            HEAD_SHA=${{ github.sha }}
          fi
          
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
          echo "PACKAGE_JSON_CHANGED=$(echo "$CHANGED_FILES" | grep -q "^package.json$" && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          npm i

      - name: Create .env file
        run: |
          echo "# .env file created by GitHub Actions" > .env
          echo "BLUR=${{ secrets.BLUR }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "SENTRY_URL=${{ secrets.SENTRY_URL }}" >> .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env

      - name: Build
        run: npm run build:all

      - name: Deploy with rsync w/ node_modules
        uses: burnett01/rsync-deployments@5.2.1
        if: steps.check_for_changes.outputs.PACKAGE_JSON_CHANGED == 'true'
        with:
          switches: -avzc --exclude="api/apps/app" --exclude=".git*" --exclude=".env.default" --exclude="biome.json" --exclude="api/api" --exclude="api/tools" --exclude="api/types" --exclude="api/utils"
          path: ./
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Deploy with rsync w/o node_modules
        uses: burnett01/rsync-deployments@5.2.1
        if: steps.check_for_changes.outputs.PACKAGE_JSON_CHANGED == 'false'
        with:
          switches: -avzc --exclude="api/apps/app" --exclude=".git*" --exclude=".env.default" --exclude="biome.json" --exclude="node_modules" --exclude="api/api" --exclude="api/tools" --exclude="api/types" --exclude="api/utils"
          path: ./
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}