name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures all history is fetched

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Run deployment steps
      uses: ./.github/actions/deploy-canopy
      secrets:
        BLUR: ${{ secrets.BLUR }}
        PORT: ${{ secrets.PORT }}
        API_KEY: ${{ secrets.API_KEY }}
        APP_ENV: ${{ secrets.APP_ENV }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        SENTRY_URL: ${{ secrets.SENTRY_URL }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        BLUR: ${{ secrets.BLUR }}
        PORT: ${{ secrets.PORT }}
        API_KEY: ${{ secrets.API_KEY }}
        APP_ENV: ${{ secrets.APP_ENV }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        SENTRY_URL: ${{ secrets.SENTRY_URL }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}