name: Manual Deploy

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures all history is fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --prod

      - name: Create .env files
        run: |
          echo "# .env file created by GitHub Actions >> ./apps/database/.env" > ./apps/database/.env
          echo "TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }} > ./apps/database/.env
          echo "TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }} > ./apps/database/.env
          
          echo "# .env file created by GitHub Actions >> ./apps/resume/.env" > ./apps/resume/.env
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" > ./apps/resume/.env
          echo "APP_ENV=${{ secrets.APP_ENV }}" > ./apps/resume/.env
          
          echo "# .env file created by GitHub Actions >> ./apps/server/.env" > ./apps/server/.env             
          echo "NODE_ENV=production" > ./apps/server/.env
          echo "BLUR=${{ secrets.BLUR }}" > ./apps/server/.env
          echo "PORT=${{ secrets.PORT }}" > ./apps/server/.env
          echo "API_KEY=${{ secrets.API_KEY }}" > ./apps/server/.env
          echo "APP_ENV=${{ secrets.APP_ENV }}" > ./apps/server/.env
          echo "SENTRY_URL=${{ secrets.SENTRY_URL }}" > ./apps/server/.env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" > ./apps/server/.env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" > ./apps/server/.env
          echo "TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}" > ./apps/server/.env
          echo "TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }}" > ./apps/server/.env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" > ./apps/server/.env
          echo "CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" > ./apps/server/.env

      - name: Build
        run: pnpm build

      - name: Deploy with rsync w/ node_modules
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzc --exclude=".git" --exclude="biome.json"
          path: ./
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}