name: Deploying Canopy

on:
  push:
    branches:
      - test

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm i

      - name: Build Apps
        env:
          PORT: ${{ secrets.PORT }}
          APP_ENV: ${{ secrets.APP_ENV }}
          BLUR: ${{ secrets.BLUR }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: npm run build -- --env DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord
        run: |
          title=$(echo ${{ github.repository }} | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
          
          npm run discord -- \
            --url ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} \
            --level success \
            --title ${{ env.title }} Status: \
            --image ${{ github.event.sender.avatar_url }} \
            --description Wafer shortbread macaroon croissant cheesecake. Oat cake dragée cake cotton candy dragée. Tart halvah marzipan oat cake jelly candy candy canes. Caramels sweet topping topping chocolate cake jujubes pudding. Apple pie brownie gummies jelly brownie marzipan. Candy jelly shortbread halvah pie halvah carrot cake. Sweet wafer wafer biscuit sesame snaps. Gummies ice cream icing
