name: Deploying Canopy

on:
  push:
    branches:
      - test

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm i

      - name: Build Apps
        env:
          PORT: ${{ secrets.PORT }}
          APP_ENV: ${{ secrets.APP_ENV }}
          BLUR: ${{ secrets.BLUR }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: npm run build

      - name: Notify Discord
        run: |
          npm run discord -- \
            --url ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} \
            --level success \
            --title ${{ github.repository }} repo \
            --author.url https://github.com/${{ github.actor }} \
            --author.name ${{ github.actor }} \
            --author.avatar ${{ github.event.sender.avatar_url }} \
            --description Status: 🎉 SUCCESS  🎉
      - name: Notify Discord Catch All
        if: ${{ failure() }}
        run: |    
          npm run discord -- \
            --url ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} \
            --level critical \
            --title ${{ github.repository }} repo \
            --author.url https://github.com/${{ github.actor }} \
            --author.name ${{ github.actor }} \
            --author.avatar ${{ github.event.sender.avatar_url }} \
            --description Status: 🚨 FAILURE  🚨